CREATE TYPE "TaxEntityType" AS ENUM ('INDIVIDUAL', 'CORPORATION');
CREATE TYPE "TaxBranchType" AS ENUM ('HEAD_OFFICE', 'BRANCH');
CREATE TYPE "TaxInvoiceStatus" AS ENUM ('ISSUED', 'CANCELLED');
CREATE TYPE "TaxInvoiceVatCategory" AS ENUM ('VAT_EXEMPT', 'VAT_7');

CREATE TABLE tax_invoice_sequences (
  tax_month CHAR(6) PRIMARY KEY,
  last_number INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT tax_invoice_sequences_month_format
    CHECK (tax_month ~ '^[0-9]{6}$'),
  CONSTRAINT tax_invoice_sequences_last_number_positive
    CHECK (last_number >= 0)
);

CREATE TABLE tax_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  user_id INTEGER NOT NULL,
  invoice_number VARCHAR(24) NOT NULL,
  entity_type "TaxEntityType" NOT NULL,
  tax_id CHAR(13) NOT NULL,
  company_or_name VARCHAR(200) NOT NULL,
  branch_type "TaxBranchType",
  branch_code CHAR(5),
  address_line VARCHAR(300) NOT NULL,
  address_village VARCHAR(100),
  street VARCHAR(150),
  subdistrict VARCHAR(120) NOT NULL,
  district VARCHAR(120) NOT NULL,
  province VARCHAR(120) NOT NULL,
  postal_code CHAR(5) NOT NULL,
  contact_email VARCHAR(320) NOT NULL,
  contact_phone VARCHAR(30) NOT NULL,
  non_vat_amount NUMERIC(14, 2) NOT NULL,
  vatable_amount NUMERIC(14, 2) NOT NULL,
  vat_amount NUMERIC(14, 2) NOT NULL,
  total_amount NUMERIC(14, 2) NOT NULL,
  pdf_file_url TEXT,
  pdf_storage_key VARCHAR(500),
  status "TaxInvoiceStatus" NOT NULL DEFAULT 'ISSUED',
  issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tax_invoices_order_fk
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT tax_invoices_user_fk
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT tax_invoices_order_unique UNIQUE (order_id),
  CONSTRAINT tax_invoices_invoice_number_unique UNIQUE (invoice_number),
  CONSTRAINT tax_invoices_tax_id_format CHECK (tax_id ~ '^[0-9]{13}$'),
  CONSTRAINT tax_invoices_branch_code_format
    CHECK (branch_code IS NULL OR branch_code ~ '^[0-9]{5}$'),
  CONSTRAINT tax_invoices_postal_code_format CHECK (postal_code ~ '^[0-9]{5}$'),
  CONSTRAINT tax_invoices_identity_branch_consistency CHECK (
    (entity_type = 'INDIVIDUAL' AND branch_type IS NULL AND branch_code IS NULL)
    OR
    (entity_type = 'CORPORATION' AND branch_type = 'HEAD_OFFICE' AND branch_code = '00000')
    OR
    (entity_type = 'CORPORATION' AND branch_type = 'BRANCH'
      AND branch_code IS NOT NULL AND branch_code <> '00000')
  ),
  CONSTRAINT tax_invoices_nonnegative_totals CHECK (
    non_vat_amount >= 0
    AND vatable_amount >= 0
    AND vat_amount >= 0
    AND total_amount >= 0
  ),
  CONSTRAINT tax_invoices_totals_consistent
    CHECK (total_amount = non_vat_amount + vatable_amount),
  CONSTRAINT tax_invoices_vat_not_above_gross CHECK (vat_amount <= vatable_amount),
  CONSTRAINT tax_invoices_pdf_fields_consistent CHECK (
    (pdf_file_url IS NULL AND pdf_storage_key IS NULL)
    OR (pdf_file_url IS NOT NULL AND pdf_storage_key IS NOT NULL)
  )
);

CREATE INDEX tax_invoices_user_issued_idx
  ON tax_invoices (user_id, issued_at DESC);

CREATE INDEX tax_invoices_status_issued_idx
  ON tax_invoices (status, issued_at DESC);

CREATE TABLE tax_invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tax_invoice_id BIGINT NOT NULL,
  product_variant_id BIGINT,
  description VARCHAR(300) NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(14, 2) NOT NULL,
  gross_amount NUMERIC(14, 2) NOT NULL,
  vat_category "TaxInvoiceVatCategory" NOT NULL,
  CONSTRAINT tax_invoice_items_invoice_fk
    FOREIGN KEY (tax_invoice_id) REFERENCES tax_invoices(id) ON DELETE RESTRICT,
  CONSTRAINT tax_invoice_items_variant_fk
    FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE SET NULL,
  CONSTRAINT tax_invoice_items_quantity_positive CHECK (quantity > 0),
  CONSTRAINT tax_invoice_items_amounts_nonnegative
    CHECK (unit_price >= 0 AND gross_amount >= 0)
);

CREATE INDEX tax_invoice_items_invoice_id_idx
  ON tax_invoice_items (tax_invoice_id, id);

CREATE TABLE user_tax_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  entity_type "TaxEntityType" NOT NULL,
  tax_id CHAR(13) NOT NULL,
  company_or_name VARCHAR(200) NOT NULL,
  branch_type "TaxBranchType",
  branch_code CHAR(5),
  address_line VARCHAR(300) NOT NULL,
  address_village VARCHAR(100),
  street VARCHAR(150),
  subdistrict VARCHAR(120) NOT NULL,
  district VARCHAR(120) NOT NULL,
  province VARCHAR(120) NOT NULL,
  postal_code CHAR(5) NOT NULL,
  contact_email VARCHAR(320) NOT NULL,
  contact_phone VARCHAR(30) NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_tax_profiles_user_fk
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT user_tax_profiles_tax_id_format CHECK (tax_id ~ '^[0-9]{13}$'),
  CONSTRAINT user_tax_profiles_branch_code_format
    CHECK (branch_code IS NULL OR branch_code ~ '^[0-9]{5}$'),
  CONSTRAINT user_tax_profiles_postal_code_format CHECK (postal_code ~ '^[0-9]{5}$'),
  CONSTRAINT user_tax_profiles_identity_branch_consistency CHECK (
    (entity_type = 'INDIVIDUAL' AND branch_type IS NULL AND branch_code IS NULL)
    OR
    (entity_type = 'CORPORATION' AND branch_type = 'HEAD_OFFICE' AND branch_code = '00000')
    OR
    (entity_type = 'CORPORATION' AND branch_type = 'BRANCH'
      AND branch_code IS NOT NULL AND branch_code <> '00000')
  ),
  CONSTRAINT user_tax_profiles_reuse_unique
    UNIQUE NULLS NOT DISTINCT (user_id, tax_id, branch_type, branch_code)
);

CREATE UNIQUE INDEX user_tax_profiles_one_default_per_user
  ON user_tax_profiles (user_id)
  WHERE is_default = TRUE;

CREATE INDEX user_tax_profiles_user_updated_idx
  ON user_tax_profiles (user_id, updated_at DESC);

COMMENT ON TABLE tax_invoice_items IS
  'Immutable line snapshots used to reproduce the exact tax breakdown on an issued invoice.';
COMMENT ON COLUMN tax_invoices.pdf_storage_key IS
  'Private storage key used by the authenticated download endpoint; do not expose the filesystem path.';
COMMENT ON TABLE tax_invoice_sequences IS
  'Transactional monthly counter for unique tax invoice numbers in the Asia/Bangkok tax month.';
