-- Adds collectible-figure metadata and deposit/balance tracking.
-- Prerequisites: products(id), product_variants(id, price), preorders,
-- orders, and order_items already exist.

CREATE TYPE "PreorderReleaseStatus" AS ENUM (
  'OnSchedule',
  'Delayed',
  'Arrived'
);

CREATE TYPE "PaymentType" AS ENUM (
  'FULL',
  'DEPOSIT'
);

CREATE TYPE "BalancePaidStatus" AS ENUM (
  'PENDING',
  'PAID'
);

CREATE TABLE manufacturers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  country VARCHAR(100),
  website_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT manufacturers_name_not_blank CHECK (length(btrim(name)) > 0),
  CONSTRAINT manufacturers_name_unique UNIQUE (name)
);

CREATE TABLE characters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  series_name VARCHAR(250) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT characters_name_not_blank CHECK (length(btrim(name)) > 0),
  CONSTRAINT characters_series_name_not_blank CHECK (length(btrim(series_name)) > 0),
  CONSTRAINT characters_name_series_unique UNIQUE (name, series_name)
);

CREATE TABLE figures_metadata (
  product_id BIGINT PRIMARY KEY,
  manufacturer_id BIGINT NOT NULL,
  character_id BIGINT,
  scale VARCHAR(100) NOT NULL,
  height_mm INTEGER,
  material VARCHAR(200),
  sculptor VARCHAR(200),
  jan_code VARCHAR(13),
  box_width_cm NUMERIC(8, 2),
  box_length_cm NUMERIC(8, 2),
  box_height_cm NUMERIC(8, 2),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT figures_metadata_product_fk
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT figures_metadata_manufacturer_fk
    FOREIGN KEY (manufacturer_id) REFERENCES manufacturers(id) ON DELETE RESTRICT,
  CONSTRAINT figures_metadata_character_fk
    FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE SET NULL,
  CONSTRAINT figures_metadata_scale_not_blank CHECK (length(btrim(scale)) > 0),
  CONSTRAINT figures_metadata_height_positive CHECK (height_mm IS NULL OR height_mm > 0),
  CONSTRAINT figures_metadata_jan_code_format
    CHECK (jan_code IS NULL OR jan_code ~ '^[0-9]{13}$'),
  CONSTRAINT figures_metadata_box_dimensions_positive CHECK (
    (box_width_cm IS NULL AND box_length_cm IS NULL AND box_height_cm IS NULL)
    OR (
      box_width_cm IS NOT NULL
      AND box_length_cm IS NOT NULL
      AND box_height_cm IS NOT NULL
      AND box_width_cm > 0
      AND box_length_cm > 0
      AND box_height_cm > 0
    )
  )
);

CREATE UNIQUE INDEX figures_metadata_jan_code_unique
  ON figures_metadata (jan_code)
  WHERE jan_code IS NOT NULL;

CREATE INDEX figures_metadata_manufacturer_id_idx
  ON figures_metadata (manufacturer_id);

CREATE INDEX figures_metadata_character_id_idx
  ON figures_metadata (character_id);

COMMENT ON TABLE figures_metadata IS
  'Figure/collectible-specific extension data; box_width_cm, box_length_cm, and box_height_cm form box_dimension_cm.';

ALTER TABLE preorders
  ADD COLUMN allow_deposit BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN deposit_amount NUMERIC(12, 2),
  ADD COLUMN full_price NUMERIC(12, 2),
  ADD COLUMN preorder_deadline TIMESTAMPTZ,
  ADD COLUMN release_month_year VARCHAR(7),
  ADD COLUMN release_status "PreorderReleaseStatus" NOT NULL DEFAULT 'OnSchedule';

UPDATE preorders AS preorder
SET full_price = variant.price
FROM product_variants AS variant
WHERE variant.id = preorder.product_variant_id;

DO $migration$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM preorders
    WHERE full_price IS NULL
  ) THEN
    RAISE EXCEPTION
      'Cannot migrate preorders: full_price could not be populated from product_variants.price';
  END IF;
END;
$migration$;

ALTER TABLE preorders
  ALTER COLUMN full_price SET NOT NULL,
  ADD CONSTRAINT preorders_full_price_positive CHECK (full_price > 0),
  ADD CONSTRAINT preorders_deposit_amount_valid CHECK (
    (
      allow_deposit = FALSE
      AND deposit_amount IS NULL
    )
    OR (
      allow_deposit = TRUE
      AND deposit_amount IS NOT NULL
      AND deposit_amount > 0
      AND deposit_amount < full_price
    )
  ),
  ADD CONSTRAINT preorders_release_month_year_format CHECK (
    release_month_year IS NULL
    OR release_month_year ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
  );

CREATE INDEX preorders_deadline_release_status_idx
  ON preorders (preorder_deadline, release_status);

ALTER TABLE order_items
  ADD COLUMN payment_type "PaymentType" NOT NULL DEFAULT 'FULL',
  ADD COLUMN remaining_balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  ADD COLUMN balance_paid_status "BalancePaidStatus" NOT NULL DEFAULT 'PAID',
  ADD COLUMN balance_due_date TIMESTAMPTZ,
  ADD CONSTRAINT order_items_remaining_balance_nonnegative
    CHECK (remaining_balance >= 0),
  ADD CONSTRAINT order_items_paid_balance_is_zero
    CHECK (balance_paid_status <> 'PAID' OR remaining_balance = 0);

ALTER TABLE orders
  ADD COLUMN payment_type "PaymentType" NOT NULL DEFAULT 'FULL',
  ADD COLUMN remaining_balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  ADD COLUMN balance_paid_status "BalancePaidStatus" NOT NULL DEFAULT 'PAID',
  ADD COLUMN balance_due_date TIMESTAMPTZ,
  ADD CONSTRAINT orders_remaining_balance_nonnegative
    CHECK (remaining_balance >= 0),
  ADD CONSTRAINT orders_paid_balance_is_zero
    CHECK (balance_paid_status <> 'PAID' OR remaining_balance = 0);

COMMENT ON COLUMN orders.remaining_balance IS
  'Order-level aggregate of order_items.remaining_balance; update it in the same payment transaction.';
COMMENT ON COLUMN orders.payment_type IS
  'Order-level summary; set to DEPOSIT when any order item uses deposit payment.';

CREATE INDEX order_items_payment_balance_idx
  ON order_items (payment_type, balance_paid_status);

CREATE INDEX order_items_balance_due_date_idx
  ON order_items (balance_due_date)
  WHERE balance_paid_status = 'PENDING';

CREATE INDEX orders_payment_balance_idx
  ON orders (payment_type, balance_paid_status);

CREATE INDEX orders_balance_due_date_idx
  ON orders (balance_due_date)
  WHERE balance_paid_status = 'PENDING';
