CREATE TABLE publishers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT publishers_name_not_blank CHECK (length(btrim(name)) > 0)
);

CREATE TABLE manga_series (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  slug VARCHAR(280) NOT NULL UNIQUE,
  publisher_id BIGINT NOT NULL REFERENCES publishers(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT manga_series_title_not_blank CHECK (length(btrim(title)) > 0)
);

CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(300) NOT NULL UNIQUE,
  name VARCHAR(300) NOT NULL,
  product_type VARCHAR(20) NOT NULL,
  volume_number INTEGER,
  publisher_id BIGINT REFERENCES publishers(id) ON DELETE RESTRICT,
  series_id BIGINT REFERENCES manga_series(id) ON DELETE RESTRICT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT products_name_not_blank CHECK (length(btrim(name)) > 0),
  CONSTRAINT products_type_allowed CHECK (product_type IN ('MANGA', 'FIGURE')),
  CONSTRAINT products_manga_series_consistent CHECK (
    (product_type = 'MANGA' AND series_id IS NOT NULL AND volume_number IS NOT NULL AND volume_number > 0)
    OR (product_type = 'FIGURE' AND series_id IS NULL AND volume_number IS NULL)
  )
);

CREATE TABLE product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  option_name VARCHAR(150) NOT NULL,
  sku VARCHAR(100) UNIQUE,
  price NUMERIC(12, 2) NOT NULL,
  stock_quantity INTEGER NOT NULL DEFAULT 0,
  weight_grams NUMERIC(10, 2),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_variants_option_not_blank CHECK (length(btrim(option_name)) > 0),
  CONSTRAINT product_variants_price_positive CHECK (price > 0),
  CONSTRAINT product_variants_stock_nonnegative CHECK (stock_quantity >= 0),
  CONSTRAINT product_variants_weight_positive CHECK (weight_grams IS NULL OR weight_grams > 0),
  CONSTRAINT product_variants_product_option_unique UNIQUE (product_id, option_name)
);

CREATE TABLE preorders (
  product_variant_id BIGINT PRIMARY KEY
    REFERENCES product_variants(id) ON DELETE CASCADE,
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ NOT NULL,
  quota_limit BIGINT,
  booked_count BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL DEFAULT 'PREORDER_OPEN',
  release_date TIMESTAMPTZ,
  CONSTRAINT preorders_date_range_valid CHECK (end_date >= start_date),
  CONSTRAINT preorders_quota_nonnegative CHECK (quota_limit IS NULL OR quota_limit >= 0),
  CONSTRAINT preorders_booked_nonnegative CHECK (booked_count >= 0),
  CONSTRAINT preorders_initial_quota_valid CHECK (
    quota_limit IS NULL OR booked_count <= quota_limit
  )
);

CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  order_number VARCHAR(100) NOT NULL UNIQUE,
  total_amount NUMERIC(12, 2) NOT NULL,
  shipping_fee NUMERIC(12, 2) NOT NULL DEFAULT 0,
  shipping_policy VARCHAR(100) NOT NULL,
  order_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  payment_status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT orders_total_nonnegative CHECK (total_amount >= 0),
  CONSTRAINT orders_shipping_nonnegative CHECK (shipping_fee >= 0)
);

CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(12, 2) NOT NULL,
  is_preorder BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT order_items_quantity_positive CHECK (quantity > 0),
  CONSTRAINT order_items_unit_price_positive CHECK (unit_price > 0),
  CONSTRAINT order_items_order_variant_unique UNIQUE (order_id, product_variant_id)
);

CREATE INDEX products_series_id_idx ON products(series_id);
CREATE INDEX products_publisher_id_idx ON products(publisher_id);
CREATE INDEX product_variants_product_id_idx ON product_variants(product_id);
CREATE INDEX orders_user_created_idx ON orders(user_id, created_at DESC);
CREATE INDEX order_items_variant_id_idx ON order_items(product_variant_id);
