ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE bank_slips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  payment_stage VARCHAR(16) NOT NULL,
  transaction_ref VARCHAR(200) NOT NULL,
  slip_hash CHAR(64) NOT NULL,
  receiver_account VARCHAR(64) NOT NULL,
  transfer_amount NUMERIC(12, 2) NOT NULL,
  transferred_at TIMESTAMPTZ NOT NULL,
  verification_provider VARCHAR(64) NOT NULL,
  verified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT bank_slips_order_fk
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT bank_slips_payment_stage_allowed
    CHECK (payment_stage IN ('INITIAL', 'BALANCE')),
  CONSTRAINT bank_slips_transaction_ref_not_blank
    CHECK (length(btrim(transaction_ref)) > 0),
  CONSTRAINT bank_slips_receiver_account_not_blank
    CHECK (length(btrim(receiver_account)) > 0),
  CONSTRAINT bank_slips_amount_positive
    CHECK (transfer_amount > 0),
  CONSTRAINT bank_slips_provider_not_blank
    CHECK (length(btrim(verification_provider)) > 0),
  CONSTRAINT bank_slips_hash_sha256_format
    CHECK (slip_hash ~ '^[0-9a-f]{64}$')
);

CREATE UNIQUE INDEX bank_slips_transaction_ref_unique
  ON bank_slips (transaction_ref);

CREATE UNIQUE INDEX bank_slips_slip_hash_unique
  ON bank_slips (slip_hash);

CREATE INDEX bank_slips_order_id_verified_at_idx
  ON bank_slips (order_id, verified_at DESC);
