CREATE TYPE "ProductWaitlistStatus" AS ENUM (
  'WAITING',
  'OFFERED',
  'CONVERTED',
  'EXPIRED',
  'CANCELLED'
);

CREATE TYPE "WaitlistNotificationStatus" AS ENUM (
  'PENDING',
  'PROCESSING',
  'SENT',
  'CANCELLED'
);

ALTER TABLE users
  ADD COLUMN line_user_id VARCHAR(100);

CREATE UNIQUE INDEX users_line_user_id_unique
  ON users (line_user_id)
  WHERE line_user_id IS NOT NULL;

ALTER TABLE product_variants
  ADD COLUMN availability_status VARCHAR(24) NOT NULL DEFAULT 'IN_STOCK',
  ADD CONSTRAINT product_variants_availability_status_allowed
    CHECK (availability_status IN ('IN_STOCK', 'OUT_OF_STOCK', 'PREORDER_CLOSED'));

UPDATE product_variants
SET availability_status = CASE
  WHEN stock_quantity > 0 THEN 'IN_STOCK'
  ELSE 'OUT_OF_STOCK'
END;

CREATE TABLE product_waitlists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_variant_id BIGINT NOT NULL,
  user_id INTEGER NOT NULL,
  queue_position BIGINT NOT NULL,
  status "ProductWaitlistStatus" NOT NULL DEFAULT 'WAITING',
  claim_token UUID,
  offer_expires_at TIMESTAMPTZ,
  offered_at TIMESTAMPTZ,
  converted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_waitlists_variant_fk
    FOREIGN KEY (product_variant_id)
    REFERENCES product_variants(id) ON DELETE CASCADE,
  CONSTRAINT product_waitlists_user_fk
    FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT product_waitlists_variant_user_unique
    UNIQUE (product_variant_id, user_id),
  CONSTRAINT product_waitlists_variant_position_unique
    UNIQUE (product_variant_id, queue_position),
  CONSTRAINT product_waitlists_position_positive
    CHECK (queue_position > 0),
  CONSTRAINT product_waitlists_offer_fields_consistent
    CHECK (
      (status = 'OFFERED'
        AND claim_token IS NOT NULL
        AND offered_at IS NOT NULL
        AND offer_expires_at IS NOT NULL)
      OR
      (status <> 'OFFERED'
        AND claim_token IS NULL
        AND offer_expires_at IS NULL)
    ),
  CONSTRAINT product_waitlists_converted_at_consistent
    CHECK ((status = 'CONVERTED') = (converted_at IS NOT NULL))
);

CREATE UNIQUE INDEX product_waitlists_claim_token_unique
  ON product_waitlists (claim_token)
  WHERE claim_token IS NOT NULL;

CREATE UNIQUE INDEX product_waitlists_one_active_offer_per_variant
  ON product_waitlists (product_variant_id)
  WHERE status = 'OFFERED';

CREATE INDEX product_waitlists_fifo_idx
  ON product_waitlists (product_variant_id, status, created_at, id);

CREATE INDEX product_waitlists_expired_offer_idx
  ON product_waitlists (offer_expires_at, product_variant_id, id)
  WHERE status = 'OFFERED';

CREATE TABLE waitlist_notification_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  waitlist_id BIGINT NOT NULL,
  status "WaitlistNotificationStatus" NOT NULL DEFAULT 'PENDING',
  attempts INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_until TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sent_at TIMESTAMPTZ,
  CONSTRAINT waitlist_notification_outbox_waitlist_fk
    FOREIGN KEY (waitlist_id)
    REFERENCES product_waitlists(id) ON DELETE CASCADE,
  CONSTRAINT waitlist_notification_outbox_waitlist_unique UNIQUE (waitlist_id),
  CONSTRAINT waitlist_notification_outbox_attempts_nonnegative CHECK (attempts >= 0),
  CONSTRAINT waitlist_notification_outbox_sent_at_consistent
    CHECK ((status = 'SENT') = (sent_at IS NOT NULL))
);

CREATE INDEX waitlist_notification_outbox_pending_idx
  ON waitlist_notification_outbox (next_attempt_at, id)
  WHERE status IN ('PENDING', 'PROCESSING');

COMMENT ON TABLE product_waitlists IS
  'FIFO claim queue for forfeited figure/collectible inventory. One user may join each variant once.';
COMMENT ON COLUMN product_waitlists.queue_position IS
  'Monotonically assigned per variant while its product_variants row is locked; created_at and id remain the authoritative FIFO order.';
COMMENT ON COLUMN product_variants.availability_status IS
  'Public availability; inventory offered to waitlist users is removed from stock_quantity until claimed or released.';
