CREATE TYPE "ShippingCarrier" AS ENUM (
  'FLASH',
  'THAI_POST'
);

ALTER TABLE figures_metadata
  ADD COLUMN actual_weight_kg NUMERIC(9, 3),
  ADD CONSTRAINT figures_metadata_actual_weight_positive
    CHECK (actual_weight_kg IS NULL OR actual_weight_kg > 0);

CREATE TABLE shipping_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrier "ShippingCarrier" NOT NULL,
  service_area_code VARCHAR(50) NOT NULL,
  min_billable_weight_kg NUMERIC(9, 3) NOT NULL DEFAULT 0,
  max_billable_weight_kg NUMERIC(9, 3),
  shipping_fee NUMERIC(12, 2) NOT NULL,
  effective_from TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  effective_until TIMESTAMPTZ,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT shipping_rates_service_area_not_blank
    CHECK (length(btrim(service_area_code)) > 0),
  CONSTRAINT shipping_rates_min_weight_nonnegative
    CHECK (min_billable_weight_kg >= 0),
  CONSTRAINT shipping_rates_weight_range_valid
    CHECK (
      max_billable_weight_kg IS NULL
      OR max_billable_weight_kg > min_billable_weight_kg
    ),
  CONSTRAINT shipping_rates_fee_nonnegative
    CHECK (shipping_fee >= 0),
  CONSTRAINT shipping_rates_effective_range_valid
    CHECK (effective_until IS NULL OR effective_until > effective_from)
);

CREATE INDEX shipping_rates_lookup_idx
  ON shipping_rates (
    carrier,
    service_area_code,
    min_billable_weight_kg,
    max_billable_weight_kg,
    effective_from
  )
  WHERE is_active = TRUE;

ALTER TABLE orders
  ADD COLUMN amount_due_now NUMERIC(12, 2) NOT NULL DEFAULT 0,
  ADD CONSTRAINT orders_amount_due_now_nonnegative
    CHECK (amount_due_now >= 0);

COMMENT ON COLUMN orders.amount_due_now IS
  'Initial amount payable at figure checkout, before payment-provider confirmation.';
