ALTER TABLE orders
  ADD COLUMN shipping_recipient_name VARCHAR(150),
  ADD COLUMN shipping_recipient_phone VARCHAR(30),
  ADD COLUMN shipping_address_line VARCHAR(300),
  ADD COLUMN shipping_address_village VARCHAR(100),
  ADD COLUMN shipping_street VARCHAR(150),
  ADD COLUMN shipping_subdistrict VARCHAR(120),
  ADD COLUMN shipping_district VARCHAR(120),
  ADD COLUMN shipping_province VARCHAR(120),
  ADD COLUMN shipping_postal_code CHAR(5),
  ADD CONSTRAINT orders_shipping_postal_code_format
    CHECK (
      shipping_postal_code IS NULL
      OR shipping_postal_code ~ '^[0-9]{5}$'
    ),
  ADD CONSTRAINT orders_shipping_address_complete
    CHECK (
      (
        shipping_recipient_name IS NULL
        AND shipping_recipient_phone IS NULL
        AND shipping_address_line IS NULL
        AND shipping_subdistrict IS NULL
        AND shipping_district IS NULL
        AND shipping_province IS NULL
        AND shipping_postal_code IS NULL
      )
      OR
      (
        shipping_recipient_name IS NOT NULL
        AND shipping_recipient_phone IS NOT NULL
        AND shipping_address_line IS NOT NULL
        AND shipping_subdistrict IS NOT NULL
        AND shipping_district IS NOT NULL
        AND shipping_province IS NOT NULL
        AND shipping_postal_code IS NOT NULL
      )
    );

CREATE TABLE order_tax_invoice_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  user_id INTEGER NOT NULL,
  entity_type "TaxEntityType" NOT NULL,
  tax_id CHAR(13) NOT NULL,
  company_or_name VARCHAR(200) NOT NULL,
  branch_type "TaxBranchType",
  branch_code CHAR(5),
  address_line VARCHAR(300) NOT NULL,
  address_village VARCHAR(100),
  street VARCHAR(150),
  subdistrict VARCHAR(120) NOT NULL,
  district VARCHAR(120) NOT NULL,
  province VARCHAR(120) NOT NULL,
  postal_code CHAR(5) NOT NULL,
  contact_email VARCHAR(320) NOT NULL,
  contact_phone VARCHAR(30) NOT NULL,
  save_for_next_time BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT order_tax_invoice_requests_order_fk
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT order_tax_invoice_requests_user_fk
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT order_tax_invoice_requests_order_unique UNIQUE (order_id),
  CONSTRAINT order_tax_invoice_requests_tax_id_format
    CHECK (tax_id ~ '^[0-9]{13}$'),
  CONSTRAINT order_tax_invoice_requests_branch_code_format
    CHECK (branch_code IS NULL OR branch_code ~ '^[0-9]{5}$'),
  CONSTRAINT order_tax_invoice_requests_postal_code_format
    CHECK (postal_code ~ '^[0-9]{5}$'),
  CONSTRAINT order_tax_invoice_requests_branch_consistency CHECK (
    (entity_type = 'INDIVIDUAL' AND branch_type IS NULL AND branch_code IS NULL)
    OR
    (entity_type = 'CORPORATION' AND branch_type = 'HEAD_OFFICE' AND branch_code = '00000')
    OR
    (entity_type = 'CORPORATION' AND branch_type = 'BRANCH'
      AND branch_code IS NOT NULL AND branch_code <> '00000')
  )
);

CREATE INDEX order_tax_invoice_requests_user_created_idx
  ON order_tax_invoice_requests (user_id, created_at DESC);
